
import Nav from "./components/Nav";


import "./styles/globals.css";



export const metadata = {
  title: "Savia DecoHome",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <div className ="holder">
            <div className ="logo">
              <img src="/IMG/img/logo.png" width= "100xpx" alt ="Savia DecoHome" />
              <h1>Savia DecoHome</h1>
            </div>
          </div>
        </header>
        <Nav/>

        {children}

      <footer>
        <p> Derechos reservados</p>
      </footer>
      </body>
    </html>
  );
}
